version: "3.7"
services:
    api:
        image: api
        ports:
            - "5000:5000"
        volumes:
            - ./api
        depends_on:
            - mongodb
    react:
        image: node
        ports:
            - 8080:3000
        volumes: 
            - ./myreact
        depends_on:
            - api
            - mongodb
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles